version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "chrimar3"
    assignees:
      - "chrimar3"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "react*"
        update-types: ["version-update:semver-major"]
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "jest*"
          - "@testing-library/*"
          - "lighthouse"
          - "pa11y"
        update-types:
          - "minor"
          - "patch"
      build-dependencies:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "terser"
          - "rollup*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
    reviewers:
      - "chrimar3"
    assignees:
      - "chrimar3"
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "docker"
      - "dependencies"
      - "automated"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
    reviewers:
      - "chrimar3"
    assignees:
      - "chrimar3"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "github-actions"
      - "ci/cd"
      - "automated"