[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Production context
[context.production]
  command = "npm run build"

[context.production.environment]
  NODE_ENV = "production"

# Staging/branch previews
[context.branch-deploy]
  command = "npm run build"

[context.branch-deploy.environment]
  NODE_ENV = "staging"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "*.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'self'"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for clean URLs
[[redirects]]
  from = "/review/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/hotel/*"
  to = "/index.html"
  status = 200

# API redirects (if needed for future API integration)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Progressive Web App
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

# Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://hotel-review-generator.com"
    sitemapPath = "/sitemap.xml"
    providers = [
      "google",
      "bing"
    ]

# Form handling (for potential contact forms)
[forms]
  # Enable form detection
  [forms.settings]
    skip_validation = false

# Functions (for potential serverless functions)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Edge functions (for advanced routing if needed)
[edge_functions]
  path = "netlify/edge-functions"

# Environment variables (non-sensitive)
[build.environment]
  SITE_URL = "https://hotel-review-generator.com"
  NODE_OPTIONS = "--max-old-space-size=4096"